// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.Bible
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("book")]
        public string Book { get; set; }

        [JsonProperty("abbr")]
        public string Abbr { get; set; }

        [JsonProperty("chapter")]
        public long? Chapter { get; set; }

        [JsonProperty("verses")]
        public long?[] Verses { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("testament")]
        public string Testament { get; set; }

        [JsonProperty("bookNumber")]
        public long? BookNumber { get; set; }

        [JsonProperty("totalChapters")]
        public long? TotalChapters { get; set; }

        [JsonProperty("totalVersesInChapter")]
        public long? TotalVersesInChapter { get; set; }

        [JsonProperty("wordCount")]
        public long? WordCount { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
